baseURL = 'localhost'
languageCode = 'en-us'
title = 'Hugo Skeleton'

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Your Name"
  authorLink = "https://yourwebsite.com/"
  description = "A boilerplate to create your own Hugo theme!"
  socialGithub = "https://github.com/name"
  socialTwitter = "https://twitter.com/name"
  socialLinkedIn = "https://linkedin.com/in/name"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
