name = 'Hugo Skeleton'
license = 'MIT'
licenselink = 'https://github.com/odhyp/hugo-skeleton/blob/master/LICENSE'
description = 'A boilerplate to create your own Hugo theme!'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/odhyp/hugo-skeleton'

# If you have a running demo of the theme
demosite = 'https://odhyp.github.io/hugo-skeleton'

# Taxonomy terms
categories = ['category 1', 'category 2']
tags = ['tag 1', 'tag 2', 'tag 3']

# If the theme has a single author
[author]
  name = 'Odhy Pradhana'
  homepage = 'https://github.com/odhyp/'
